---
-
  hosts: masterAndWorkers
  tasks:
    -
      name: "Editamos el /etc/hosts"
      lineinfile:
        dest: /etc/hosts
        line: "{{item.line}}"
      with_items:
        - { line: '10.0.1.20  vm-master' } 
        - { line: '10.0.1.10  vm-worker01' }
        - { line: '10.0.1.11  vm-worker02' }
        - { line: '10.0.1.12  vm-nfs' }
    
    - name: "Creamos el directorio nfs para el file system compartido /srv/nfs"
      file:
        path: /nfs
        state: directory
        owner: adminUsername
        group: adminUsername

    - name: Montamos el NFS al master y a los workers
      mount:
        src: 10.0.1.12:/srv/nfs
        path: /nfs
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs

    - name: Añadimos le NFS al directorio /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: '10.0.1.12:/srv/nfs    /nfs   nfs auto,noatime,nolock,bg,nfsvers=4,intr,tcp,actimeo=1800 0 0'
        state: present
        create: yes
    - 
      name: "modprobe"
      command: modprobe br_netfilter    
    
    - name: "Activamos masquerade"
      firewalld:
       masquerade: yes
       state: enabled
       permanent: yes
       zone: dmz

    - 
      name: "reload service firewalld"
      systemd:
        name: firewalld
        state: reloaded
    
    - name: Add netbridge config ip6
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: 'net.bridge.bridge-nf-call-ip6tables = 1'
        state: present
        create: yes

    - name: Add netbridge config ip4
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: 'net.bridge.bridge-nf-call-iptables = 1'
        state: present
        create: yes

    - name: update sysctl
      command: sysctl --system    

    - 
      name: "Remove swapfile from /etc/fstab"
      mount:
        name: swap
        fstype: swap
        state: absent

    - 
      name: "Turn swap off"
      shell: swapoff -a

    - name: Eliminamos la línea del fichero /etc/fstab que monta en el arranque el swap
      lineinfile:
        path: /etc/fstab
        regexp: "swap" 
        state: absent
      
    
    - 
      name: "Add docker repo"
      command:
        cmd: "yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo"
        
   
    -
      name: "Instalamos docker"
      command:
        cmd: "yum install docker-ce docker-ce-cli containerd.io -y"
        

    -
      name: "Iniciando servicio docker"
      service:
        enabled: true
        name: "{{ item }}"
        state: started
      with_items:
        - docker
        
    -
      name: Add kubernetes repo
      yum_repository:
        name: kubernetes
        description: Kubernetes repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        enabled: 1
        gpgcheck: 1
        repo_gpgcheck: 1
        

    -
      name: "Instalamos kubernetes"
      dnf:
        name: ['kubelet', 'kubeadm', 'kubectl']
        disable_excludes: kubernetes

    -
      name: "Iniciando servicio kubelet"
      service:
        enabled: true
        name: kubelet
        state: started
        
